### ISSUE TITLE
SPA blows URL path away on load so page reload doesn't work

### ISSUE THREAD

**Issue by imylomylo** [ittus/vuejs-firebase-shopping-cart#1]
Hi,

I built it for production and uploaded it to s3 3 times with some minor changes.  I don't know if it's a vue-router issue or a webpack config issue.

Summary:
Go to URL: https://s3-ap-southeast-2.amazonaws.com/christopher.programming.bucket/second/index.html

SPA loads no probs but the address bar changes to https://s3-ap-southeast-2.amazonaws.com/

And page refresh doesn't work.

Cheers

Details:

Minor changes to index.html where the build.js script is src'd.

**ORIGINAL**
URL: https://s3-ap-southeast-2.amazonaws.com/christopher.programming.bucket/index.html

As it was originally
```
    <script src="/dist/build.js"></script>
  </body>
</html>
```

**FIRST CHANGE**
URL: https://s3-ap-southeast-2.amazonaws.com/christopher.programming.bucket/first/index.html

From

```
    <script src="/dist/build.js"></script>
  </body>
</html>
```

To
```
    <script src="build.js"></script>
  </body>
</html>
```

And uploaded the build.js files into same folder as index.html
```
/index.html
/build.js
/build.js.map
```

And this wipes away the URL bath back to the root (e.g. no bucket name in url)

**SECOND CHANGE**
URL: https://s3-ap-southeast-2.amazonaws.com/christopher.programming.bucket/second/index.html
From

```
    <script src="/dist/build.js"></script>
  </body>
</html>
```

To
```
    <script src="dist/build.js"></script>
  </body>
</html>
```
So files are
```
/index.html
/dist/build.js
/dist/build.js.map
```

URL disappears back to .........amazonaws.com

**Comment by ittus** [comment]
Hi,
Do you use static website hosting feature of AWS S3?
http://docs.aws.amazon.com/AmazonS3/latest/dev/HostingWebsiteOnS3Setup.html

**Comment by imylomylo** [comment]
Yes.  Is there a routing step there I've missed?  I'll check.

**Comment by imylomylo** [comment]
Additionally if you go to http://christopher.programming.bucket.s3-website-ap-southeast-2.amazonaws.com/

first/
second/
third/

it strips away and returns to the root.

In webpack.config.js changing 
```
    publicPath: 'http://christopher.programming.bucket.s3-website-ap-southeast-2.amazonaws.com/',
```
and going to fourth/ has same behaviour.

Bucket permissions seem to be configured correctly with this test index.html file in the dist directory of fourth test case.
http://christopher.programming.bucket.s3-website-ap-southeast-2.amazonaws.com/fourth/dist/index.html

Hope that helps

**Comment by imylomylo** [comment]
And another bucket configured with simpler vue app:
http://vuesample.businessapps.com.au.s3-website-ap-southeast-2.amazonaws.com/first-level-test/
also in the root
http://vuesample.businessapps.com.au.s3-website-ap-southeast-2.amazonaws.com/

(console errors are to do with missing cordova.js and favicon.ico files)

**Comment by imylomylo** [comment]
Same on non-aws-s3 website hosting:   https://www.vetopower.net/vueshoptest/index.html   (https://www.vetopower.net/vueshoptest/dist/index.html works)  just being served out of apache.

Cheers

**Comment by imylomylo** [comment]
Two things are at play here.

```
const router = new VueRouter({
	// mode: 'history',
	routes
});
```
Going to hash mode (default) in the router solves it and puts a # into the URL.
To fix this # url is beyond the framework but suggestions on this page https://router.vuejs.org/en/essentials/history-mode.html should help anyone with having pretty urls.

http://christopher.programming.bucket.s3-website-ap-southeast-2.amazonaws.com/hashmode

And this needs to go in the Redirection rules for S3 static hosting

```
<RoutingRules>
  <RoutingRule>
    <Condition>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <HostName>zanon.io</HostName> <!-- add your domain name here -->
      <ReplaceKeyPrefixWith>#/</ReplaceKeyPrefixWith>
    </Redirect>
  </RoutingRule>
</RoutingRules>
```
