### ISSUE TITLE
Problems connecting to firebase

### ISSUE THREAD

**Issue by marcowenk** [ittus/vuejs-firebase-shopping-cart#11]
Hi, 
seems like connecting to firebase is not working for me. Can help me and list the steps I need to do? Would really appreciate and definitely send over some "coffee". :)

Best, 
Marco

**Comment by ittus** [comment]
Hi Marco,
Thank you for interested in my repository.

Did you see any error in browser's console?
Did you try importing data [here ](https://github.com/ittus/vuejs-firebase-shopping-cart/blob/master/data/vuejs-shopping-cart-products-export.json) to your firebase database?

**Comment by marcowenk** [comment]
Hi, 
thanks for the quick answer. 
Importing worked fine. 
Console has this output:

<img width="749" alt="Bildschirmfoto 2019-07-05 um 18 50 02" src="https://user-images.githubusercontent.com/8598325/60736027-e2f11e00-9f55-11e9-9e5e-4550fdaaaf3d.png">

**Comment by ittus** [comment]
Hi Marco,

It's only warning. You can read more about it here
https://stackoverflow.com/questions/53139432/importing-only-auth-package-from-firebase-module

We won't fix this at the moment.
