### ISSUE TITLE
Npm run serve

### ISSUE THREAD

**Issue by pirouetti** [ittus/vuejs-firebase-shopping-cart#12]
I added my configuration starting with:
const firebaseConfig = {
}

to firebaseConfig.js 
When
npm run serve
it shows the error:

This dependency was not found:
* firebase in ./src/config/firebaseConfig.js 
To install it, you can run: npm install --save firebase

npm install --save firebase does not help neither.

**Comment by ittus** [comment]
It should include firebase lib already. Have you tried `npm install` in root folder?

https://github.com/ittus/vuejs-firebase-shopping-cart/blob/c117a294f76ac71a7b33d66ae61863432597038d/package.json#L13
