### ISSUE TITLE
Please include license

### ISSUE THREAD

**Issue by trongthanh** [ittus/vuejs-firebase-shopping-cart#2]
Hi,

This code base is really useful for people learning Vue.js, vuex and stuff. I'm using it as base for a demo with some PWA enhancement.

I would like to know the license applied for this repo so that I can inherit it from my side.

Thanks.

**Comment by ittus** [comment]
Thank you very much for your asking.

This project is under [CC Attribution License](https://creativecommons.org/licenses/by/4.0/). Please feel to play with it.

Best Regards,
