### ISSUE TITLE
Funding this Open Source Shopping Cart

### ISSUE THREAD

**Issue by diegotco** [ittus/vuejs-firebase-shopping-cart#7]
I love this Shopping cart because is clean, simple, minimalist , very fast... And hosting free

And of course I am not alone. There is a lot of people who think similar than me

We, the community, can thrive this and make this Vuejs+Firebase shopping cart better than shopify but for free

I believe code contributors must be paid in order to get this done :)

Are you with me?

I have 3 options to do this:

1. A group here https://salt.bountysource.com/
2. Post the project here: https://liberapay.com/
both above may charge you more than 5% 

3. Pay in bitcoin directly to any coder throug a Lightning Network 
This means zero cost transfer

Any comments?

**Comment by ittus** [comment]
Hi @diegotco,

Thank you very much for your interesting in this project.

At first, the purpose of this project is creating a simple demonstration of Shopping Cart using VueJS and Firebase. Anybody can fork this project and create more features product (add management page, payment, affiliate features...). I would like to keep it as simple as possible. 

There are other great shopping cart repository with more features, for example [this](https://github.com/sdras/sample-vue-shop)

Please let me know if you have further questions.

**Comment by diegotco** [comment]
"I would like to keep it as simple as possible"

I respect this. And this is why I love this repo :)

Thank you @ittus :)
